name: Build the backend

on:
  push:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image for Backend
      run: |
        docker build -t inheir-backend:latest .
